import { RouteInfo } from './sidebar.metadata';
export const ROUTES: RouteInfo[] = [

  {
    path: 'dashboard',
    title: 'Dashboard',
    iconType: 'feather',
    icon: 'grid',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: 'profile',
    title: 'My Profile',
    iconType: 'feather',
    icon: 'user',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: 'jobs',
    title: 'My Jobs',
    iconType: 'feather',
    icon: 'list',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: 'chat',
    title: 'Chat',
    iconType: 'feather',
    icon: 'message-square',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: 'plans-membership',
    title: 'Plans & Transactions',
    iconType: 'feather',
    icon: 'dollar-sign',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  // {
  //   path: 'account-settings',
  //   title: 'Account Settings',
  //   iconType: 'feather',
  //   icon: 'settings',
  //   class: '',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   submenu: [],
  // },
 

  // {
  //   path: 'manage-coins',
  //   title: 'Manage Coins',
  //   iconType: 'feather',
  //   icon: 'alert-circle',
  //   class: '',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   submenu: [],
  // },
  // {
  //   path: 'reports',
  //   title: 'Reports',
  //   iconType: 'feather',
  //   icon: 'layout',
  //   class: '',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   submenu: [],
  // },
];
